Parameters: 
  GithubOwner:
    Type: String
    Default: corbantjoyce
    Description: "Github repo owner"
  GithubRepo:
    Type: String
    Default: website
    Description: "Github repo name"
  GithubOAuthToken:
    Type: String
    Description: "Github personal access token"
  PipelineBucket:
    Type: String
    Default: codepipeline-us-east-2-430342469624
    Description: "S3 bucket to store build"